<a href="https://colab.research.google.com/github/and-is/learning-pytorch/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Autograd provides automatic differentiation for tensor operations, enabling gradient computations.

In [ ]:
import torch

In [ ]:
x = torch.tensor(3.0, requires_grad=True)

In [ ]:
y = x**2

In [ ]:
y
# internal computation graph showing that power function was used, which is the
# backward function of this step

In [ ]:
y.backward()
# this function does the backward propagation now, this will calculate gradients in the backward direction,
# i.e. the gradient of y w.r.t x

In [ ]:
x.grad

tensor(6.)

In [ ]:
z = torch.sin(y)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
print(x.grad)
# y.grad will fail as it is not a leaf node, by default, gradients for intermediates are not calculated.

tensor(-5.4668)


In [ ]:
m = torch.tensor(5.5)  # input
n = torch.tensor(0.0)  # true label (binary)

w = torch.tensor(1.0, requires_grad=True)  # weight
b = torch.tensor(0.0, requires_grad=True)  # bias

In [ ]:
def binary_cross_entropy_loss(pred,targ):
  epsilon = 1e-8
  pred = torch.clamp(pred, epsilon, 1-epsilon)
  return -(targ * torch.log(pred) + (1-targ) * torch.log(1-pred))

In [ ]:
z = w * m + b

In [ ]:
z

tensor(5.5000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)

In [ ]:
y_pred

tensor(0.9959, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_cross_entropy_loss(y_pred,n)

In [ ]:
loss

tensor(5.5041, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor(5.4776)
tensor(0.9959)


In [ ]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)

In [66]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [67]:
y.backward()

In [68]:
x.grad

tensor([1.3333, 2.6667, 4.0000])

Gradients get accumulated when we run forward and backward pass multiple times, i.e. gradients get added.
\
So we need to clear out the gradients before running pass again

In [70]:
x.grad.zero_()
# Gotta clear grads before each epochs

tensor([0., 0., 0.])

During predictions time, we need no backward pass. So we can turn gradient tracking false by these ways:
- requires_grad_(false)
- detach()
- torch.no_grad()

In [72]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [73]:
x

tensor([1., 2., 3.])

In [75]:
y = x**2

In [76]:
y

tensor([1., 4., 9.])

In [77]:
z = x.detach()

In [81]:
z
# z is simply x but without gradient tracking now, can use z instead of x now.

tensor([1., 2., 3.])

In [82]:
x = torch.tensor(2.0, requires_grad=True)

In [83]:
with torch.no_grad():
  y = x ** 2

In [85]:
y
# This way running y inside no_grad function disables gradient tracking here.

tensor(4.)