<a href="https://colab.research.google.com/github/and-is/learning-pytorch/blob/main/data_classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset and Dataloader class in pytorch, how to use.

These classes that decouple data loading and training with data in a efficient way. Can be used to perform mini batch gradient descent efficiently.
/
Dataset class gives length and individual item based on indices, dataloader looks over batching.

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
# a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples = 10,
    n_features = 2,     # total, informative and redundant features
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42     # for reproducibility
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
X.shape

(10, 2)

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):

    # Any transformations we wish to apply can be applied here with ease like resizing, b/w ing, data augmentation and so on.
    return self.features[index], self.labels[index]


In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
dataloader

In [ ]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.7774,  1.5116],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.0683, -0.9701]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------


Thus, our randomly created batches are ready to go. Dataloader is an iterable yk
/
Can also add num_workers to perform tasks in parallel.

We can use collate function to combine a list of samples from a dataset into a single batch in a custom manner.