<a href="https://colab.research.google.com/github/and-is/learning-pytorch/blob/main/tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors and ways to generate them

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
  print('GPU yes!')
  print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
  print("No GPU, only CPU")

GPU yes!
GPU: Tesla T4


In [ ]:
# empty function simply allocates memory space and shows what garbage is stored there
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
# initialize values with 0s, also .ones() possible
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# however rand() gives new values everytime the code is run.
# for same output, we can use manual_seed()
torch.rand(2,3)

tensor([[0.7494, 0.0556, 0.2902],
        [0.7438, 0.2116, 0.1147]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)
# if same seed used, same values every time.

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# for custom values, can pass arrays or tuples
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10,2)
# same way as list thing in python, start stop step

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0,10,10)
# need 10 evenly spaced values between 0 and 10

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5)
# identity square matrix of that order

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)
# shape of 3x3, with all elements 5

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)
# make a tensor with same shape as x

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3690753098104661348]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(x)
# shows an error as rand generates float but x has all integers

Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x

tensor(4)

In [ ]:
x.to(torch.float32)

tensor(4.)

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor(0.2627)

Mathematical Operations

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239]])

In [ ]:
x + 2

tensor([[2.7876, 2.4183, 2.9014],
        [2.9969, 2.7565, 2.2239]])

In [ ]:
x - 2

tensor([[-1.2124, -1.5817, -1.0986],
        [-1.0031, -1.2435, -1.7761]])

In [ ]:
x * 2

tensor([[1.5752, 0.8366, 1.8028],
        [1.9938, 1.5130, 0.4478]])

In [ ]:
x / 2

tensor([[0.3938, 0.2092, 0.4507],
        [0.4984, 0.3783, 0.1119]])

In [ ]:
(x*100) // 3

tensor([[26., 13., 30.],
        [33., 25.,  7.]])

In [ ]:
((x * 100)//3)%2

tensor([[0., 1., 0.],
        [1., 1., 1.]])

In [ ]:
x**2

tensor([[0.6203, 0.1750, 0.8125],
        [0.9938, 0.5723, 0.0501]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051]])
tensor([[0.5989, 0.4450, 0.7278],
        [0.4563, 0.3389, 0.6211]])


In [ ]:
a+b
a-b
a*b
a/b
a**b
# and so on element wise things

tensor([[0.5269, 0.6008, 0.6266],
        [0.2421, 0.7972, 0.9399]])

In [ ]:
c = torch.tensor([1,-2,-3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2,  3,  4])

In [ ]:
d = torch.tensor([1.2,2.7,4.9])
torch.round(d)

tensor([1., 3., 5.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)
# useful to keep things within a range

tensor([2.0000, 2.7000, 3.0000])

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [ ]:
torch.sum(e)
# overall sum

tensor(30)

In [ ]:
torch.sum(e, dim=0)
# sum along columns

tensor([13,  9,  8])

In [ ]:
torch.sum(e, dim=1)
# sum along rows

tensor([18, 12])

In [ ]:
torch.mean(e)
# only works on float, not long dtype

tensor(4.6667)

In [ ]:
torch.mean(e, dim=0)
# similar to sum

tensor([4., 4., 6.])

In [ ]:
torch.median(e)

tensor(4.)

In [ ]:
torch.max(e)

tensor(8.)

In [ ]:
torch.mean(e)

tensor(4.6667)

In [ ]:
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)
# finding standard deviation

tensor(3.0768)

In [ ]:
torch.var(e)
# variance

tensor(9.4667)

In [ ]:
torch.argmax(e)
# posn of largest element

tensor(4)

In [ ]:
torch.argmin(e)

tensor(1)

In [ ]:
f = torch.randint(size=(2,3), low=1, high=10)
g = torch.randint(size=(3,2), low=2, high=9)
print(f)
print(g)

tensor([[6, 3, 9],
        [4, 6, 7]])
tensor([[6, 6],
        [2, 6],
        [3, 2]])


In [ ]:
torch.matmul(f,g)

tensor([[69, 72],
        [57, 74]])

In [ ]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

In [ ]:
torch.dot(vec1, vec2)

tensor(11)

In [ ]:
f

tensor([[6, 3, 9],
        [4, 6, 7]])

In [ ]:
torch.transpose(f, 0, 1)
# transpose which dimension by which

tensor([[6, 4],
        [3, 6],
        [9, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=1, high=10, dtype=torch.float32)
torch.det(h)

tensor(24.)

In [ ]:
torch.inverse(h)

tensor([[ 0.0000e+00,  1.6667e-01, -8.3333e-02],
        [-5.0000e-01,  5.0000e-01,  1.3039e-08],
        [ 2.0000e+00, -2.1667e+00,  5.8333e-01]])

In [ ]:
i = torch.randint(size=(3,3), low=1, high=10, dtype=torch.float32)
j = torch.randint(size=(3,3), low=1, high=10, dtype=torch.float32)
print(i)
print(j)

tensor([[2., 4., 4.],
        [8., 6., 1.],
        [1., 6., 2.]])
tensor([[3., 4., 3.],
        [2., 9., 5.],
        [1., 6., 4.]])


In [ ]:
i<j

tensor([[ True, False, False],
        [False,  True,  True],
        [False, False,  True]])

In [ ]:
i>j

tensor([[False, False,  True],
        [ True, False, False],
        [False, False, False]])

In [ ]:
i == j

tensor([[False,  True, False],
        [False, False, False],
        [ True,  True, False]])

In [ ]:
i != j

tensor([[ True, False,  True],
        [ True,  True,  True],
        [False, False,  True]])

In [ ]:
i >= j

tensor([[False,  True,  True],
        [ True, False, False],
        [ True,  True, False]])

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 2., 2.],
        [3., 7., 1.]])

In [ ]:
torch.log(k)

tensor([[0.6931, 0.0000,   -inf],
        [1.6094, 0.0000,   -inf]])

In [ ]:
torch.exp(k)

tensor([[  7.3891,   2.7183,   1.0000],
        [148.4132,   2.7183,   1.0000]])

In [ ]:
torch.sqrt(k)

tensor([[1.4142, 1.0000, 0.0000],
        [2.2361, 1.0000, 0.0000]])

In [ ]:
torch.sigmoid(k)

tensor([[0.8808, 0.7311, 0.5000],
        [0.9933, 0.7311, 0.5000]])

In [ ]:
torch.softmax(k, dim=0)
# which dim basis to sum up, here we assigned row wise

tensor([[0.0474, 0.0067, 0.7311],
        [0.9526, 0.9933, 0.2689]])

In [ ]:
torch.relu(k)

tensor([[0., 2., 2.],
        [3., 7., 1.]])

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.3847, 0.4521, 0.5569],
        [0.9952, 0.0015, 0.0813]])
tensor([[0.4907, 0.2130, 0.4603],
        [0.1386, 0.0277, 0.5662]])


Inplace Operations: underscore is the key

In [ ]:
m.add_(n)
# This value is assigned to m here

tensor([[1.3662, 0.8781, 1.4775],
        [1.2725, 0.0569, 1.2137]])

In [ ]:
m.relu_()

tensor([[1.3662, 0.8781, 1.4775],
        [1.2725, 0.0569, 1.2137]])

In [ ]:
m

tensor([[1.3662, 0.8781, 1.4775],
        [1.2725, 0.0569, 1.2137]])

Copying a Tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
# copying directly obviously makes them mutable, i.e. changes get carried upon
print(id(a))
b = a
print(id(b))

139291380817552
139291380817552


In [ ]:
c = a.clone()
print(id(c))

139291380933360


Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# create tensor on GPU now
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a

tensor([[0.3503, 0.6555, 0.7667],
        [0.2269, 0.7555, 0.6458]])

In [ ]:
b = a.to(device)

In [ ]:
b + 5

tensor([[5.3503, 5.6555, 5.7667],
        [5.2269, 5.7555, 5.6458]], device='cuda:0')

Reshaping Tensors

In [ ]:
a = torch.ones(4,4)

In [ ]:
a.reshape(2,2,2,2)
# product should be same always

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.3041, 0.9867, 0.1290, 0.6887],
         [0.1637, 0.0899, 0.3139, 0.1219],
         [0.3516, 0.2316, 0.2847, 0.3520]],

        [[0.2828, 0.2420, 0.4928, 0.5772],
         [0.3771, 0.2440, 0.8994, 0.1041],
         [0.9193, 0.6201, 0.3658, 0.0623]]])

In [ ]:
b.permute(2,0,1)
# switch dimensions in order 2 0 1, i.e. 4*2*3 now

tensor([[[0.3041, 0.1637, 0.3516],
         [0.2828, 0.3771, 0.9193]],

        [[0.9867, 0.0899, 0.2316],
         [0.2420, 0.2440, 0.6201]],

        [[0.1290, 0.3139, 0.2847],
         [0.4928, 0.8994, 0.3658]],

        [[0.6887, 0.1219, 0.3520],
         [0.5772, 0.1041, 0.0623]]])

In [ ]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
# typical image size
c = torch.rand(226,226,3)
# unsqueeze adds a new dimension, this adds at 0th position
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
d = torch.rand(1,20)

In [ ]:
d.squeeze(0).shape
# squeeze basically removes a dimension

torch.Size([20])

NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])

In [ ]:
e = torch.from_numpy(c)

In [ ]:
type(e)

torch.Tensor